homeassistant:
  # Name of the location where Home Assistant is running
  name: LittleBits
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 120
  unit_system: metric
  time_zone: Europe/Lisbon
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
automation old: !include automations_old.yaml
automation: !include automations.yaml
config:

http:
  api_password: !secret HTTP_PASSWORD
  base_url: !secret my_base_url_wport
  server_port: 8125
  ssl_certificate: /home/homeassistant/.homeassistant/ssl/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/ssl/privkey.pem 
  # cors_allowed_origins:
  #   - https://google.com
  #   - https://home-assistant.io
  #use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.2.0/24
    - 192.168.1.0/24
    - !secret allowed_IP
  ip_ban_enabled: True
  login_attempts_threshold: 5

ifttt:
    key: !secret ifttt_key 
 
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time. 
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: en

# logging level setup
logger:
  default: warning
  logs:
    homeassistant.components.scrip: info
  #  logs:
  #  homeassistant.components.media_player: debug
    

# Bonjour 
zeroconf:

  
## INCLUDES

group: !include groups.yaml
switch: !include devices/switches.yaml

sensor: !include sensors.yaml
weblink: !include web_links.yaml
