- platform: asuswrt
  host: 192.168.2.1
  username: !secret asuswrt_username 
  password: !secret asuswrt_passsword
  protocol: telnet
  interval_seconds: 120
  consider_home: 360
  track_new_devices: no
