- platform: snmp
  host: elCastro
  name: elcastro_snmp
  baseoid: 1.3.6.1.2.1.1.5.0
  community: public
  version: 2c

- platform: waqi
  token: !secret waqi_token
  locations: lisboa  

- platform: yr