homeassistant:
  customize:
    
    media_player.salabits:
      emulated_hue: false
      emulated_hue_name: "Playroom Kodi"
      icon: mdi:kodi

##Define neccessary components
input_select:
  salabits_power_options:
    name: salabits
    options:
      - 'On'
      - Restart
      - Shutdown
      - Sleep
      - Hibernate
      - 'Off'
    icon: mdi:desktop-tower

switch:
- platform: wake_on_lan
  mac_address: !secret salaBits_MAC
  name: "salabits_WOL"
  host: salabits
  hidden: true

## Define state changes except WOL-ON.
## Currently used: http://www.airytec.com/en/switch-off/get?version=3.5.0.950
shell_command:
  shutdown_power_salabits: !secret salabits_shutdown_power_salabits
  restart_power_salabits: !secret salabits_restart_power_salabits
  sleep_power_salabits: !secret salabits_sleep_power_salabits
  hibernate_power_salabits: !secret salabits_hibernate_power_salabits


automation: 
## Run script depending on selected input option
  - id: salabits_power_restart
    alias: salabits_power_restart
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.salabits_power_options
      to: Restart
    action:
      - service: shell_command.restart_power_salabits

  - id: salabits_power_shutdown
    alias: salabits_power_shutdown
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.salabits_power_options
      to: Shutdown
    action:
      - service: shell_command.shutdown_power_salabits
 
  - id: salabits_power_sleep
    alias: salabits_power_sleep
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.salabits_power_options
      to: Sleep
    action:
      - service: shell_command.sleep_power_salabits

  - id: salabits_power_hibernate
    alias: salabits_power_hibernate
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.salabits_power_options
      to: Hibernate
    action:
      - service: shell_command.hibernate_power_salabits
  ## Run WOL-ON if ON is selected as input option
  - id: salabits_power_poweron
    alias: salabits_power_poweron
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.salabits_power_options
      to: 'On'
    action:
      - service: switch.turn_on
        entity_id: switch.salabits_wol

## reflect ON/OFF state from sensor in the current input option (has delay) 
  - id: salabits_power_wol_triggered
    alias: salabits_power_wol_triggered
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.salabits_wol
    action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.salabits_power_options
        option : >
          {% if is_state("switch.salabits_wol", "on") %}
          On
          {%-elif is_state("switch.salabits_wol", "off") %}
          Off
          {% endif %}

sensor:
  - platform: snmp
    host: salabits
    name: salabits_snmp
    baseoid: 1.3.6.1.2.1.1.5.0
    community: public
    version: 2c

group:
  salabits_automations:
    name: 'SalaBits Automations'
    entities:
    - automation.salabits_power_sleep
    - automation.salabits_power_hibernate
    - automation.salabits_power_restart
    - automation.salabits_power_shutdown
    - automation.salabits_power_poweron
    - automation.salabits_power_wol_triggered

  # Unused for this device
  # salabits_scenes:
  #   name: 'SalaBits Scenes'
  #   entities:

  
  salabits:
    name: 'SalaBits'
    control: hidden
    entities:
    - group.salabits_pc
    - group.salabits_automations
    #- group.salabits_scenes
  
  salabits_pc:
    name: 'SalaBits PC'
    control: hidden
    entities:
    - switch.salabits_wol
    - input_select.salabits_power_options
    view: false
 






