
sensor:

  - platform: mqtt
    name: "Living Room Temperature"
    state_topic: "home/livingroom/temperature"
    qos: 0
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Living Room Humidity"
    state_topic: "home/livingroom/humidity"
    qos: 0
    unit_of_measurement: "%"

    
